In [2]:
import numpy as np

In [3]:
a = 56
b = 88
c = 99
tb = [a,b,c]

for n in tb:
    print(f"________[ - {n} - ]________")

________[ - 56 - ]________
________[ - 88 - ]________
________[ - 99 - ]________


<h1>Analiza pakietu NUMPY</h1>
<p style="font-size:14pt;color:crimson;">ważne funkcjonalności pakietu</p>

In [4]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.empty(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
v = np.arange(1,89,3)
print(v)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88]


In [8]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [9]:
lt = [6.6,5e+45,5.,6,True,120,0,0.09]
nplist = np.array(lt)
print(nplist)

[6.6e+00 5.0e+45 5.0e+00 6.0e+00 1.0e+00 1.2e+02 0.0e+00 9.0e-02]


In [10]:
kr = {9,3,56,7}
knp = np.array(kr)
print(knp)
print(type(knp))

{56, 9, 3, 7}
<class 'numpy.ndarray'>


In [11]:
nb = [908,25,3,6,8,9,63,7.77,35,67,8,9,12,34,9,0,53,56,4667]
nnp = np.array(nb)
nnp

array([9.080e+02, 2.500e+01, 3.000e+00, 6.000e+00, 8.000e+00, 9.000e+00,
 6.300e+01, 7.770e+00, 3.500e+01, 6.700e+01, 8.000e+00, 9.000e+00,
 1.200e+01, 3.400e+01, 9.000e+00, 0.000e+00, 5.300e+01, 5.600e+01,
 4.667e+03])

In [12]:
nnp.sort()
nnp

array([0.000e+00, 3.000e+00, 6.000e+00, 7.770e+00, 8.000e+00, 8.000e+00,
 9.000e+00, 9.000e+00, 9.000e+00, 1.200e+01, 2.500e+01, 3.400e+01,
 3.500e+01, 5.300e+01, 5.600e+01, 6.300e+01, 6.700e+01, 9.080e+02,
 4.667e+03])

In [13]:
la = [8,13,4]
lb = [123,6,90]

fullab = la+lb
fullab

[8, 13, 4, 123, 6, 90]

In [14]:
na = np.array([1,5,89,3])
nb = np.array([8,9,14,56])
nc = np.array([83,455,6,122])

big = np.concatenate((na,nb,nc))
print(big)

[  1   5  89   3   8   9  14  56  83 455   6 122]


In [15]:
big.sort()
print(big)

[  1   3   5   6   8   9  14  56  83  89 122 455]


Macierze w NUMPY

In [16]:
zx = [[5,7],[9,11]]
print(zx)
print(zx[0])
print(zx[0][0])

[[5, 7], [9, 11]]
[5, 7]
5


In [17]:
x = np.array([[67,4],[9,12]])
print(x)
print(x[0,0])

[[67  4]
 [ 9 12]]
67


In [18]:
y = np.array([[88,14],[10,20]])
p = np.concatenate((x,y),axis=0)
p

array([[67, 4],
 [ 9, 12],
 [88, 14],
 [10, 20]])

In [19]:
#tworzenie wektora
prosta = np.arange(12)
prosta

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [23]:
pp = prosta.reshape(4,3)
print(pp)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [24]:
mc = np.array([[2,3],[5,6],[19,7]])
print(mc)

[[ 2  3]
 [ 5  6]
 [19  7]]


In [25]:
bc = mc.reshape(2,3)
bc

array([[ 2, 3, 5],
 [ 6, 19, 7]])

In [27]:
vec = bc.reshape(1,6)
print(vec)

[[ 2  3  5  6 19  7]]


In [28]:
w = np.array([[1,2,3,4],[6,11,17,21],[38,48,54,88]])
print(w)

[[ 1  2  3  4]
 [ 6 11 17 21]
 [38 48 54 88]]


In [29]:
print(w[w<5])

[1 2 3 4]


In [30]:
pc = (w>=5)
print(w[pc])

[ 6 11 17 21 38 48 54 88]


In [31]:
pv  = (w%2==0)
print(w[pv])

[ 2  4  6 38 48 54 88]


In [32]:
c = w[(w>2)&(w<21)]
print(c)

[ 3  4  6 11 17]


In [33]:
d = w[(w<4)|(w>23)]
print(d)

[ 1  2  3 38 48 54 88]


In [34]:
dane = np.array([1,3,8])
ones = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [35]:
dane+ones

array([2, 4, 9])

In [36]:
dane-ones

array([0, 2, 7])

In [37]:
dane*tw

array([ 2, 6, 24])

In [38]:
dane/tw

array([0.5 , 1.5 , 2.66666667])

In [39]:
tab = np.array([[1,6],[27,19]])
print(tab)

[[ 1  6]
 [27 19]]


In [40]:
print(tab.sum(axis=0))

[28 25]


In [41]:
print(tab.sum(axis=1))

[ 7 46]


In [42]:
print(tab.mean(axis=0))
print(tab.mean(axis=1))

[14.  12.5]
[ 3.5 23. ]


In [43]:
print(tab.std(axis=0))
print(tab.std(axis=1))

[13.   6.5]
[2.5 4. ]


In [44]:
print(tab*1.87)

[[ 1.87 11.22]
 [50.49 35.53]]


In [45]:
print(tab.max(axis=0))

[27 19]


In [46]:
print(tab.min())

1


In [49]:
print(tab.prod())

3078
