In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
import matplotlib.pyplot as plt

In [6]:
obj = pd.Series([4,7,-9,3,5,6,7,5,7])
obj

0 4
1 7
2 -9
3 3
4 5
5 6
6 7
7 5
8 7
dtype: int64

In [7]:
print(type(obj))

<class 'pandas.core.series.Series'>


In [8]:
obj.values

array([ 4, 7, -9, 3, 5, 6, 7, 5, 7])

In [9]:
obj.value_counts()

7 3
 5 2
 4 1
-9 1
 3 1
 6 1
dtype: int64

In [10]:
obj2 = pd.Series([45,6,8,9,12,34,6], index=['a','b','c','n','x','y','z'])
obj2

a 45
b 6
c 8
n 9
x 12
y 34
z 6
dtype: int64

In [12]:
obj2['n']

9

In [13]:
obj2['a']=11
obj2

a 11
b 6
c 8
n 9
x 12
y 34
z 6
dtype: int64

In [14]:
obj2[obj2>10]

a 11
x 12
y 34
dtype: int64

In [15]:
sdata = {'Warszawa':45120,'Kraków':38970,'Lublin':35634,'Gdańsk':39670}
obj3 = pd.Series(sdata)
obj3

Warszawa 45120
Kraków 38970
Lublin 35634
Gdańsk 39670
dtype: int64

In [16]:
miasta = ['Poznań','Kraków','Rzeszów','Lublin']
obj4 = pd.Series(sdata,index=miasta)
obj4

Poznań NaN
Kraków 38970.0
Rzeszów NaN
Lublin 35634.0
dtype: float64

In [17]:
pd.isnull(obj4)

Poznań True
Kraków False
Rzeszów True
Lublin False
dtype: bool

In [18]:
obj3+obj4

Gdańsk NaN
Kraków 77940.0
Lublin 71268.0
Poznań NaN
Rzeszów NaN
Warszawa NaN
dtype: float64

In [19]:
obj4.name = "liczba wniosków"
obj4.index.name = 'miasta'
obj4

miasta
Poznań NaN
Kraków 38970.0
Rzeszów NaN
Lublin 35634.0
Name: liczba wniosków, dtype: float64

In [27]:
k = "Kraków"
w = "Warszawa"
miasta = []
for _ in range(3):
    miasta.append(k)
    miasta.append(w)


miasta.sort(reverse=True)
miasta

['Warszawa', 'Warszawa', 'Warszawa', 'Kraków', 'Kraków', 'Kraków']

In [28]:
data = {
    'miasto':miasta,
    'rok':[2017,2018,2019,2018,2019,2020],
    'pop':[2.7,2.75,3.05,0.85,0.92,1.01]
}

frame = pd.DataFrame(data)
frame

miasto 
 rok 
 pop 
 
 
 
 
 0 
 Warszawa 
 2017 
 2.70 
 
 
 1 
 Warszawa 
 2018 
 2.75 
 
 
 2 
 Warszawa 
 2019 
 3.05 
 
 
 3 
 Kraków 
 2018 
 0.85 
 
 
 4 
 Kraków 
 2019 
 0.92 
 
 
 5 
 Kraków 
 2020 
 1.01

In [30]:
frame2 = pd.DataFrame(data,columns=['rok','miasto','pop','wsp'],index=['jeden','dwa','trzy','cztery','pięć','sześć'])
frame2

rok 
 miasto 
 pop 
 wsp 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 NaN 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 NaN 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 NaN 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 NaN 
 
 
 pięć 
 2019 
 Kraków 
 0.92 
 NaN 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 NaN

In [31]:
frame2['miasto']

jeden Warszawa
dwa Warszawa
trzy Warszawa
cztery Kraków
pięć Kraków
sześć Kraków
Name: miasto, dtype: object

In [32]:
frame2.rok

jeden 2017
dwa 2018
trzy 2019
cztery 2018
pięć 2019
sześć 2020
Name: rok, dtype: int64

In [33]:
frame2['wsp'] = 19.99
frame2

rok 
 miasto 
 pop 
 wsp 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 19.99 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 19.99 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 19.99 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 19.99 
 
 
 pięć 
 2019 
 Kraków 
 0.92 
 19.99 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 19.99

In [34]:
frame2['wsp'] = np.arange(6.)
frame2

rok 
 miasto 
 pop 
 wsp 
 
 
 
 
 jeden 
 2017 
 Warszawa 
 2.70 
 0.0 
 
 
 dwa 
 2018 
 Warszawa 
 2.75 
 1.0 
 
 
 trzy 
 2019 
 Warszawa 
 3.05 
 2.0 
 
 
 cztery 
 2018 
 Kraków 
 0.85 
 3.0 
 
 
 pięć 
 2019 
 Kraków 
 0.92 
 4.0 
 
 
 sześć 
 2020 
 Kraków 
 1.01 
 5.0

In [39]:
daty = pd.date_range("20230404",periods=6)
daty

DatetimeIndex(['2023-04-04', '2023-04-05', '2023-04-06', '2023-04-07',
               '2023-04-08', '2023-04-09'],
              dtype='datetime64[ns]', freq='D')

In [40]:
fr = pd.DataFrame(np.random.rand(6,4),index=daty,columns=list('ABCD'))
fr

A 
 B 
 C 
 D 
 
 
 
 
 2023-04-04 
 0.572677 
 0.983749 
 0.326099 
 0.489824 
 
 
 2023-04-05 
 0.924098 
 0.827133 
 0.648659 
 0.461308 
 
 
 2023-04-06 
 0.588944 
 0.873944 
 0.521349 
 0.355095 
 
 
 2023-04-07 
 0.400794 
 0.755923 
 0.506174 
 0.704078 
 
 
 2023-04-08 
 0.242254 
 0.295022 
 0.160909 
 0.693866 
 
 
 2023-04-09 
 0.080614 
 0.323164 
 0.577163 
 0.465608

In [42]:
fr.head(2)

A 
 B 
 C 
 D 
 
 
 
 
 2023-04-04 
 0.572677 
 0.983749 
 0.326099 
 0.489824 
 
 
 2023-04-05 
 0.924098 
 0.827133 
 0.648659 
 0.461308

In [43]:
fr.tail(3)

A 
 B 
 C 
 D 
 
 
 
 
 2023-04-07 
 0.400794 
 0.755923 
 0.506174 
 0.704078 
 
 
 2023-04-08 
 0.242254 
 0.295022 
 0.160909 
 0.693866 
 
 
 2023-04-09 
 0.080614 
 0.323164 
 0.577163 
 0.465608

In [45]:
fr.sample(3)

A 
 B 
 C 
 D 
 
 
 
 
 2023-04-04 
 0.572677 
 0.983749 
 0.326099 
 0.489824 
 
 
 2023-04-06 
 0.588944 
 0.873944 
 0.521349 
 0.355095 
 
 
 2023-04-05 
 0.924098 
 0.827133 
 0.648659 
 0.461308

In [49]:
nfr = fr.to_numpy()
print(nfr)
print(type(fr))
print(type(nfr))

[[0.57267652 0.9837493  0.32609882 0.48982448]
 [0.92409801 0.82713322 0.64865912 0.46130809]
 [0.58894355 0.87394394 0.5213489  0.35509514]
 [0.40079385 0.75592348 0.5061736  0.70407762]
 [0.24225448 0.29502209 0.16090919 0.69386624]
 [0.08061428 0.32316423 0.57716346 0.46560772]]
<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


In [50]:
fr.describe()

A 
 B 
 C 
 D 
 
 
 
 
 count 
 6.000000 
 6.000000 
 6.000000 
 6.000000 
 
 
 mean 
 0.468230 
 0.676489 
 0.456726 
 0.528297 
 
 
 std 
 0.296363 
 0.294196 
 0.180297 
 0.140149 
 
 
 min 
 0.080614 
 0.295022 
 0.160909 
 0.355095 
 
 
 25% 
 0.281889 
 0.431354 
 0.371118 
 0.462383 
 
 
 50% 
 0.486735 
 0.791528 
 0.513761 
 0.477716 
 
 
 75% 
 0.584877 
 0.862241 
 0.563210 
 0.642856 
 
 
 max 
 0.924098 
 0.983749 
 0.648659 
 0.704078

In [53]:
trfr = fr.T
trfr

2023-04-04 
 2023-04-05 
 2023-04-06 
 2023-04-07 
 2023-04-08 
 2023-04-09 
 
 
 
 
 A 
 0.572677 
 0.924098 
 0.588944 
 0.400794 
 0.242254 
 0.080614 
 
 
 B 
 0.983749 
 0.827133 
 0.873944 
 0.755923 
 0.295022 
 0.323164 
 
 
 C 
 0.326099 
 0.648659 
 0.521349 
 0.506174 
 0.160909 
 0.577163 
 
 
 D 
 0.489824 
 0.461308 
 0.355095 
 0.704078 
 0.693866 
 0.465608

In [52]:
fr

A 
 B 
 C 
 D 
 
 
 
 
 2023-04-04 
 0.572677 
 0.983749 
 0.326099 
 0.489824 
 
 
 2023-04-05 
 0.924098 
 0.827133 
 0.648659 
 0.461308 
 
 
 2023-04-06 
 0.588944 
 0.873944 
 0.521349 
 0.355095 
 
 
 2023-04-07 
 0.400794 
 0.755923 
 0.506174 
 0.704078 
 
 
 2023-04-08 
 0.242254 
 0.295022 
 0.160909 
 0.693866 
 
 
 2023-04-09 
 0.080614 
 0.323164 
 0.577163 
 0.465608

In [54]:
fr.sort_index(axis=1,ascending=False)

D 
 C 
 B 
 A 
 
 
 
 
 2023-04-04 
 0.489824 
 0.326099 
 0.983749 
 0.572677 
 
 
 2023-04-05 
 0.461308 
 0.648659 
 0.827133 
 0.924098 
 
 
 2023-04-06 
 0.355095 
 0.521349 
 0.873944 
 0.588944 
 
 
 2023-04-07 
 0.704078 
 0.506174 
 0.755923 
 0.400794 
 
 
 2023-04-08 
 0.693866 
 0.160909 
 0.295022 
 0.242254 
 
 
 2023-04-09 
 0.465608 
 0.577163 
 0.323164 
 0.080614

In [55]:
fr.sort_values(by='B')

A 
 B 
 C 
 D 
 
 
 
 
 2023-04-08 
 0.242254 
 0.295022 
 0.160909 
 0.693866 
 
 
 2023-04-09 
 0.080614 
 0.323164 
 0.577163 
 0.465608 
 
 
 2023-04-07 
 0.400794 
 0.755923 
 0.506174 
 0.704078 
 
 
 2023-04-05 
 0.924098 
 0.827133 
 0.648659 
 0.461308 
 
 
 2023-04-06 
 0.588944 
 0.873944 
 0.521349 
 0.355095 
 
 
 2023-04-04 
 0.572677 
 0.983749 
 0.326099 
 0.489824

In [61]:
objX = pd.Series([4.5,7.2,-5.6,5],index=['d','a','w','h'])
objX

d 4.5
a 7.2
w -5.6
h 5.0
dtype: float64

In [62]:
objY = objX.reindex(['a','w','h','d','q'])
objY

a 7.2
w -5.6
h 5.0
d 4.5
q NaN
dtype: float64

In [63]:
objG = pd.Series(['blue','yellow','purple'],index=[0,2,4])
objG

0 blue
2 yellow
4 purple
dtype: object

In [64]:
objG.reindex(range(6),method='ffill')

0 blue
1 blue
2 yellow
3 yellow
4 purple
5 purple
dtype: object

In [66]:
dataf = pd.DataFrame(np.arange(16).reshape((4,4)),
                     index=['Kraków','Warszawa','Lublin','Rzeszów'],
                     columns=['cecha1','cecha2','cecha3','cecha4'])
dataf

cecha1 
 cecha2 
 cecha3 
 cecha4 
 
 
 
 
 Kraków 
 0 
 1 
 2 
 3 
 
 
 Warszawa 
 4 
 5 
 6 
 7 
 
 
 Lublin 
 8 
 9 
 10 
 11 
 
 
 Rzeszów 
 12 
 13 
 14 
 15

In [67]:
dataf['cecha3']

Kraków 2
Warszawa 6
Lublin 10
Rzeszów 14
Name: cecha3, dtype: int64

In [69]:
dataf.loc[['Kraków','Lublin'],['cecha1','cecha3']]

cecha1 
 cecha3 
 
 
 
 
 Kraków 
 0 
 2 
 
 
 Lublin 
 8 
 10

In [72]:
dataf.iloc[[2,1],[3,0,1]].T

Lublin 
 Warszawa 
 
 
 
 
 cecha4 
 11 
 7 
 
 
 cecha1 
 8 
 4 
 
 
 cecha2 
 9 
 5

In [75]:
v1 = np.arange(2,19,2)
print(v1.T)

[ 2  4  6  8 10 12 14 16 18]


In [76]:
dataf.loc[:'Lublin','cecha3']

Kraków 2
Warszawa 6
Lublin 10
Name: cecha3, dtype: int64

In [78]:
dataf.iloc[:,:3][dataf.cecha3>10]

cecha1 
 cecha2 
 cecha3 
 
 
 
 
 Rzeszów 
 12 
 13 
 14

In [84]:
s="lajkonik"
print(s)
print(s[2])
print(s[2:7])
print(s[:6])
print(s[4:])
print(s[-1])
print(s[-2])

lajkonik
j
jkoni
lajkon
onik
k
i


In [89]:
print(s[::-1])

kinokjal


In [90]:
imiona = ["Jan","Olga","Leon","Jola","Henio","Maria"]

In [92]:
imp = imiona[::2]
imp

['Jan', 'Leon', 'Henio']

In [94]:
imn = imiona[1::2]
imn

['Olga', 'Jola', 'Maria']